services:
  app:
    build: .
    container_name: ip-app
    # ports:
    #   - "9080:8080"
    environment:
      - TEMPORAL_ADDR=temporal:7233
      - TASK_QUEUE=images-storage
    networks:
      - is-network
      - temporal-network
      - render-network

networks:
  is-network:
    external: true
  render-network:
    external: true
  temporal-network:
    external: true
